set nocompatible

filetype plugin indent on
syntax on

set encoding=utf-8

set autoindent
set backspace=indent,eol,start
set complete-=i
set smarttab

set ignorecase
set smartcase
set incsearch
set hlsearch
set wrapscan

set hidden
set laststatus=2
set ruler
set number
set wildmenu

set report=0
set display+=lastline
set scrolloff=5
set sidescrolloff=5

set ttyfast
set lazyredraw

set nolist
set formatoptions+=j
set autoread

set noswapfile
set nowritebackup
set nobackup

set undofile
set undodir=$HOME/.vim/files/undo

set cursorline
set termguicolors
colorscheme acme
