#!/bin/sh

if [ -r "${XDG_CONFIG_HOME}/x11/Xresources" ]; then
  xrdb -load "${XDG_CONFIG_HOME}/x11/Xresources"
fi

# Set keyboard layout and key refresh rate.
setxkbmap -model pc104 -layout us -option compose:ralt
xset r rate 320 35

# Disable mouse acceleration.
xinput set-prop 'SteelSeries Kana v2 Gaming Mouse' 'libinput Accel Speed' -1

# Disable monitor standby, suspend and off.
xset dpms 0 0 0

# Disable screensaver.
xset s noblank
xset s off

# Start urxvt terminal daemon.
urxvtd -q -o -f

exec startxfce4
