#!/bin/sh

if [ -r "${HOME}/.Xresources" ]; then
  xrdb -merge "${HOME}/.Xresources"
fi

# Set keyboard layout and swap right alt with right ctrl.
setxkbmap -model pc104 -layout us -option compose:ralt

# Disable mouse acceleration.
xinput set-prop 'SteelSeries Kana v2 Gaming Mouse' 'libinput Accel Speed' -1

# Disable monitor standby, suspend and off.
xset dpms 0 0 0

# Disable screensaver.
xset s noblank
xset s off

# Start urxvt terminal daemon.
urxvtd -q -o -f

exec startxfce4
